LADSoft/OrangeC

- appveyor.yml
Hi again David,
With this file merged, and after a trivial signup procedure at http://appveyor.com, AppVeyor can automatically build every commit and artifact the resulting executables.
For example, here are some executables resulting from a build of the current master branch: https://ci.appveyor.com/project/ysangkok/orangec/build/artifacts
The project I have configured will only built my own fork, this is why I made this pull request.
I don't see any disadvantages to enabling this. AppVeyor will send you an email after each build by default, but it is easy to disable this.
Regards,
Janus
> Add AppVeyor CI configuration file

- src/ocide/dbgmain.c
use same wording and suppress empty prints
> minimal message adjustment for "exit with exit code"

- appveyor.yml
- src/clang.mak
- src/ocide/HEADER.H
There's no reason this PR shouldn't work except that if clang has more problems than GCC on windows (which it probably does, but we'll find out about that, now won't we). I essentially just copy/pasted from the MINGW64 makefile to edit it up so that it hopefully works properly. Once we can get the warnings all in from clang, gcc, and MSVC that should be a lot of items we could fix and hopefully get less confusing things to happen with.
(this PR is about #148 )
> Adding clang as a compiler to build from on APPVEYOR

- src/clibs/alloc/aalloc.c
- src/clibs/alloc/calloc.c
- src/clibs/alloc/farmem.c
- src/clibs/alloc/farmems.c
- src/clibs/alloc/free.c
- src/clibs/alloc/malloc.c
- src/clibs/alloc/realloc.c
- src/clibs/alloc/strdup.c
- src/clibs/stdinc/io
- src/clibs/stdinc/io.h
- src/clibs/stdinc/libp.h
- src/clibs/threads/mtx.c
Includes one big thing I found in <io> that exists in stdinc for some reason, as well as a minor removal of a useless line in mtx.c
I want to take this PR to ask a better question: lea.c I see exists and I wonder if it should be updated at all to use a better malloc algorithm, https://github.com/rampantpixels/rpmalloc seems incredibly good for what is needed and supports Windows, although it is c11 based.
I bring this up because I looked around and found out most other C libraries use an entirely different methodology to malloc, most base theirs around some derivation of dlmalloc (which is what lea.c is based on), FreeBSD uses jemalloc (I don't recommend this because it has a lot of logging built into it, which is something I don't prefer because you can't remove it for performance …
> This is for some minor issues I found in alloc

- doc/Tools.md
Just stumbled over this *slightly* outdated part of the documentation. On the second thought you may want to add something like "if ORANGEC environment variable is set it must be set to..." (if this could lead to conflicts).
Actually I'm not sure that there's a reason to keep `ORANGEC` environment variable.., It is still in the sources, isn't it?
> update docs for #75

- src/ocide/ocide.c
fixes #258 
The "problems" with the old implementation:
* "test.cwa.bak" opens as workspace
* "TEST.CWA" doesn't open as workspace
Both should work as expected with the PR (I haven't checked if there are other places which would benefit from something like this...)
> ocide: more secure check for cwa extension on open

- src/occ/parse/ccmain.cpp
- src/occ/parse86/piper.cpp
- src/occ/preproc/preproc.cpp
[VC](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/getcwd-wgetcwd?view=vs-2017) defines it as:
```c
// defined in <direct.h>
char *_getcwd(
char *buffer,
int maxlen
);
```
[POSIX definition](https://linux.die.net/man/3/getcwd):
```c
// defined in  <unistd.h>
char *getcwd(char *buf, size_t size);
```
Note: In general it would be better to use `HAVE_UNISTD_H` instead of `GCCLINUX`.
> improve linux builds

- src/occ/parse/declcons.cpp
- src/occ/parse/declcpp.cpp
- src/occ/parse/mangle.cpp
- src/occ/parse/template.cpp
OCC crashes at https://github.com/LADSoft/OrangeC/blob/60fcd108fc530b1db25d02af0ee4f1e351d76348/src/occ/parse/declcons.cpp#L1712-L1714 when funcparams->sp is null, this is what is causing the crash with #366 I've fixed the crashing by just having PromoteConstructorArgs exit immediately if funcparams->sp is null, however, in #366 's case it should not be null, and I should investigate more as to why OCC isn't recognizing that the function's overload/constructor exists in this case... I think it's something to do with std::forward, but who knows...
> Fix occ crashing with a pair of functions

- .gitignore
- src/occ/middle/iconst.cpp
- src/occ/x86/outasm.cpp
I notice #377 and checked, as far as I can see there are precisely 2 instances where this happens and I've fixed them fairly simply.  (note: since when FPF is initialized setZero is called I removed the setZero call, if you want me to re-add the setZero call just in case I'm fine with it but IIRC it should still work the same)
> Fix using the mem* operations on FPF

- README.md
- doc/occil.md
I haven't checked if the part of `OCCIL_ROOT` in the README is still true, but I think if it is both the reference and the check should be adjusted to use the common Orange C variables (as outlined in #369 there is no big benefit in having MSIL in a separated installation, so the common settings and paths should be used).
> Minor updates concerning OCCIL integration

- doc/Technical Documentation/Compiler Intermediate Language format.md
- doc/Technical Documentation/IEEE-695 Object File format.md
There's some points where we REALLY need a table but markdown as a standard (not github, github has a custom markdown) does not have table support and wants you to use HTML, which I'm far too lazy to learn HTML when 15 seconds of applying regex can get something decent and readable
For best effects of seeing the results just look at how the files themselves look in my repo, much cleaner with separated lines, don't you think?
Also of note: I'm submitting this PR for the `split` branch and not the master.
> Fix some documentation for easier readability online

- src/ocpp/ppInclude.cpp
- src/ocpp/ppInclude.h
This fixes an issue with #include_next specifically with the ability to
include files that are in the same directory as the compiled one, this
is an error and is solved by simply checking if the path has been
completed on its go through, if it has been, return that we have an
error (empty filename). I was originally going to do this
overcomplicated error handling mechanism when I realized that:
1. It was way too complex for anything useful
2. It was far too much effort
3. It would not change the root of the problem, that which the original
compiled directory was somehow being included despite #include_next
by definition skipping it.
These 8 lines fix points 1, 2, and 3.
I tested this against the q.bat setup given as a dump from the last PR, the error message should probably propagate the …
> Fix include next issue #523

- src/ocpp/ppInclude.cpp
- src/util/Utils.cpp
- src/util/Utils.h
This time against the libcxx branch.
This is to fix the bug where the last include directory gets ignored, this is fixed by not assuming the buffer for the paths is empty if the path is empty.
> Include next fix

- src/ocpp/ppInclude.cpp
This is a special case to just make sure nothing breaks due to having an empty user search include path during skipIncludeDepth.
> Finally fixes for both with and without include files

- src/clibs/cpp/libcxx/src/experimental/memory_resource.cpp
- src/clibs/cpp/libcxx/src/filesystem/directory_iterator.cpp
- src/clibs/cpp/libcxx/src/filesystem/filesystem_common.h
- src/clibs/cpp/libcxx/src/filesystem/int128_builtins.cpp
- src/clibs/cpp/libcxx/src/filesystem/operations.cpp
- src/clibs/cpp/libcxx/src/include/apple_availability.h
- src/clibs/cpp/libcxx/src/include/atomic_support.h
- src/clibs/cpp/libcxx/src/include/config_elast.h
- src/clibs/cpp/libcxx/src/include/refstring.h
- src/clibs/cpp/libcxx/src/support/runtime/exception_fallback.ipp
- src/clibs/cpp/libcxx/src/support/runtime/exception_glibcxx.ipp
- src/clibs/cpp/libcxx/src/support/runtime/exception_libcxxabi.ipp
- src/clibs/cpp/libcxx/src/support/runtime/exception_libcxxrt.ipp
- src/clibs/cpp/libcxx/src/support/runtime/exception_msvc.ipp
- src/clibs/cpp/libcxx/src/support/runtime/exception_pointer_cxxabi.ipp
- src/clibs/cpp/libcxx/src/support/runtime/exception_pointer_glibcxx.ipp
- src/clibs/cpp/libcxx/src/support/runtime/exception_pointer_msvc.ipp
- src/clibs/cpp/libcxx/src/support/runtime/exception_pointer_unimplemented.ipp
- src/clibs/cpp/libcxx/src/support/runtime/new_handler_fallback.ipp
- src/clibs/cpp/libcxx/src/support/runtime/stdexcept_default.ipp
- src/clibs/cpp/libcxx/src/support/runtime/stdexcept_vcruntime.ipp
- src/clibs/makefile
- src/occparse/cppbltin.cpp
This adds the sources for the __libcpp_atomic_* so we don't need to have those erroneous builtins anymore, what we should have is define the actual builtins used for the file (e.g. the __atomic_exchange_n, etc.) and define that we have atomics from that. This only affects the build to allow the libcxx branch to properly build everything except that __builtin_strcmp in <typeinfo> and that mutex instantiation in line 658 of locale.cpp
> Make libcxx compile more things by adding missing includes

- src/ocpp/ppInclude.cpp
This fixes the bug that reopened #523 this should not be responsible for the:
```
occparse Version 6.0.45.1 Copyright (C) LADSoft 2006-2020
Error( 11)    C:\OrangeC\include\__config(513):  Syntax error: ) expected
Error( 11)    C:\OrangeC\include\__config(517):  Syntax error: ) expected
Error( 11)    C:\OrangeC\include\__config(521):  Syntax error: ) expected
Error( 11)    C:\OrangeC\include\__config(531):  Syntax error: ) expected
Error( 11)    C:\OrangeC\include\__config(535):  Syntax error: ) expected
Error( 11)    C:\OrangeC\include\__config(536):  Syntax error: ) expected
Error( 11)    C:\OrangeC\include\__config(543):  Syntax error: ) expected
Error( 11)    C:\OrangeC\include\__config(547):  Syntax error: ) expected
Error( 11)    C:\OrangeC\include\__config(551):  Syntax error: ) …
```
> Fix bug by skipping files properly

- src/ocpp/ppInclude.cpp
The current issue that I cannot fix is the searching from the path of
the last included file, because with files that go into deeper
directories, this functionality is 100% broken, not that it probably
wouldn't cause problems down the line, due to it skipping possibly
necessary imports and seriously messes with anything related to
\#include_next or any functionality that decides to respect the ordering
of include paths, which this absolutely, totally, completely, destroys.
Removing this functionality is also a breaking change, so if we're going
to do this, I would recommend doing this now, when it rears the problems
in implementing #include_next and anything that relies on system files.
DO NOT PULL THIS PR UNTIL COMPLETELY TESTED!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! …
> Fix all problems I know how to fix

- src/ocpp/ppInclude.cpp
It turns out I accidentally forgot a not in my boolean logic,
whoooooooooooops
The logic should only skip the one file if we're not doing #include_next since the empty dir is already skipped if we're #include_next'ing
> Fixes include_next for empty include path

- src/omake/MakeMain.cpp
This PR is part of #568 and this is only the beginning, not planning on tackling #569 until way later on, this is just the beginning, the main thing preventing me from adding more is that we can't add multiple long-forms for a single short form with our current solution, maybe we can make a superclass that defines that there is an infinite amount of equivalent long-forms for a single short-form?
> Begin adding other make commands to OMake

- src/clibs/platform/win32/wininc/win32/structur.h
See discussion in a5e60ed2fbc6764986e60846346933fd0175fb03.
> fixed typo in structur.h

- src/clibs/stdinc/stdint.h
- src/occ/beIntrins.cpp
This *SHOULD* make the beintrins check a little more organized and may or may not take less time overall. Technically this is a O(2n) function, but it should still be faster than the O(n * m) function we had before. 
Also this fixes everything for C and C++ stdint, maybe unless we need to unrestrict stuff after C99 for the __STDC_LIMIT_MACROS and __STDC_CONSTANT_MACROS stuff, however this does allow the constructs to compile in C++ and I haven't had time to check 3 different standards to see the exacts necessary...
> Fix stdint.h and use an unordered_map with custom hasher for beintrins

- src/omake/MakeMain.cpp
follow up to 9542dfe, using https://www.gnu.org/software/make/manual/make.html#Options-Summary as template
fair warning:
* this was a browser-only edit, only tested by CI (compiles)
* to improve the compatibility to GNU make and other make implementations the longopt argument needs to be an _array_ of strings, not a single array; you may consider this as a feature request and could add the additional long-options GNU make knows about (often from other make implementations) from the template [should this be a new FR?]
> omake long-options compatibility to GNU make

- src/clibs/stdinc/sys/types.h
Stuff like `_PID_T_` is queried in different projects and defined in at least the MinGW headers, so I've added the relevant ones.
Please don't feel any urge to pull that in, it is more a suggestion but also a general design issue.
Note: different projects additionally/alternatively query the defines that are found in at least glibc's types.h, like `__pid_t_defined´ it may be reasonable to check for/define both (or not...).
> definition of MinGW-style type defines

- doc/general/lsdbghelper.md
* add note about `%PATH%` (which is important for running generated programs outside of the compiler)
* format all switches identical
* fixed a typo of `aa1()`
feel free to close and do other/minor adjustments to the file as you see fit
> minor editorial for debughelper

- src/objlib/ObjIeee.h
- src/objlib/ObjIeeeBinaryRead.cpp
- src/occparse/stmt.cpp
Fixes #651 such that any [[noreturn]] type attribute works on non-void functions.
This was accomplished simply by removing the error statement when checking if a non-void function has the attribute.
> Fix #651 [[noreturn]] should work on non-void functions

- src/oasm/AsmExpr.cpp
I noticed this issue where xleft->FVAL + xright->FVAL were being pointed out to me by Visual Studio during an Analysis run, as it turns out the issue at hand is that the FVAL property can be accessed due to an enum being a part of the class. I checked to make sure no other instances of something like this was happening, and thankfully this is the only case.
> Fix rare issue where oasm could be potentially generating incorrect code

- src/clibs/cpp/libcxx/test/support/platform_support.h
- src/clibs/platform/win32/wininc/fileapi.h
- src/clibs/stdinc/inttypes.h
- src/occparse/c.h
- src/occparse/expr.cpp
The fixes here are for a lot of tests failing not having correct support
in creating a temporary file name, tests for inttypes not having all of
the correct integer formats for C++, and basetypes not being checked
when searching for candidates' symbol pointers, causing crashes when
types are const or volatile.
I'm also working on an issue where noexcept specifiers on specific constructors aren't being applied correctly and am trying to track down in-code where that can be happening but due to the sheer number of places debugging that will probably take a few days.
> Add fixes to improve many issues with current libcxx tests

- HISTORY.md
This is no complete work, but fixes the most obvious issues, it now renders "well enough" and has appropriate sub-headings which can be linked, to.
I hope this may help a bit with the missing entry for the current version spotted with #701 (of course, also in src/releasenotes.txt)
One thing that is open:
Os it Frank or Franck? What were his referenced changes?
> markdown cleanup HISTORY

- src/clibs/platform/win32/lscrtl/makefile
- src/occopt/beinterfdefs.h
- src/occparse/c.h
- src/occparse/declcpp.cpp
- src/occparse/lex.cpp
- src/occparse/libcxx.cpp
- src/occparse/occparse.cpp
- src/occparse/osutil.cpp
- src/occparse/osutil.h
- src/ocpp/PreProcessor.cpp
[[__attributes__]] and [[attributes]] support mainly along with elifdef and elifndef We still have a long way to go but this basic support structure should be there
Also there's a bug with compiling this fixes along the way. Also, nullptr, can't forget that thing
And the fact that you don't need every keyword type We'll probably have to slightly modify the internal workings based on what the actual C standard deprecates (such as _Noreturn) later
This also fixes a compilation error related to the renaming of wininc
> Add beginning stages of C2x support

- src/occparse/lex.cpp
- src/omake/semaphores.h
Apparently the error was being generated from the count not being high enough, when I merge this with the mainline it works perfectly.
This also contains a fix for a premature move with MSVC.
This also adds the `'` separator to C2x
> Fix the C2X issue
